name: Deploy React to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Install Node.js and dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: ''

    - run: npm install --no-lockfile
    - run: npm run build

    # 3. Copy files to EC2
    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "*"           # Copies all files
        target: "/var/myproject/aws-testing"

    # 4. Restart PM2 on EC2
    - name: Restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/myproject/aws-testing
          /home/ubuntu/.nvm/versions/node/v20.18.3/bin/pm2 restart server || \
          /home/ubuntu/.nvm/versions/node/v20.18.3/bin/pm2 start server.cjs --name server
